using System.Text.Json;
using MapWright.Core.Playbooks;
using MapWright.Core.Profile;
using MapWright.Core.Spec;

namespace MapWright.Core.Matching;

public sealed record MappingOptions
{
    /// <summary>Default: "&lt;source&gt;__&lt;target&gt;" from the system names.</summary>
    public string? Id { get; init; }
    public string? Title { get; init; }
    public string Version { get; init; } = "0.1.0";

    /// <summary>Default: now.</summary>
    public DateTimeOffset? CreatedAt { get; init; }
    public ConfidencePolicy ConfidencePolicy { get; init; } = new();
}

/// <summary>
/// Generates a mapping spec from a source and a target profile: one row per target value field, paired with
/// source fields through the business concepts the domain playbooks recognise on both sides.
/// </summary>
public static class MappingGenerator
{
    public const string Author = "MapWright";

    public static MappingDocument Generate(SystemProfile source, SystemProfile target, PlaybookLibrary library, MappingOptions? options = null)
    {
        options ??= new();
        var builder = new MappingBuilder(RecognisedField.From(source, library), library, options.ConfidencePolicy);
        var targets = RecognisedField.From(target, library);
        var mappings = targets.Select((t, i) => builder.Map(t, $"M{i + 1:000}")).ToList();
        var used = mappings.SelectMany(m => m.Sources).Select(s => s.Path).ToHashSet(StringComparer.Ordinal);
        var orphans = builder.Sources.Where(s => !used.Contains(s.Path)).Select(Orphan).ToList();
        var findings = builder.Findings().Concat(ProfileFindings(source, target, mappings)).Select((f, i) => f with { Id = $"F{i + 1:000}" }).ToList();

        var createdAt = options.CreatedAt ?? DateTimeOffset.UtcNow;
        var usedPlaybooks = library.Active
            .Where(p => p.Process is not null || mappings.Any(m => m.DomainPlaybook == p.Reference))
            .Select(p => new PlaybookRef { Name = p.Id, Version = p.Version })
            .ToList();

        return new()
        {
            SpecVersion = MappingDocument.CurrentSpecVersion,
            Id = options.Id ?? $"{Slug(source.System)}__{Slug(target.System)}",
            Title = options.Title ?? $"{source.System} → {target.System} mapping",
            Version = options.Version,
            CreatedAt = createdAt,
            Description = $"Generated by {Author} from the {source.System} and {target.System} profiles.",
            Source = SystemRef(source),
            Target = SystemRef(target),
            ConfidencePolicy = options.ConfidencePolicy,
            Inputs = [.. Inputs(source, SystemSide.Source), .. Inputs(target, SystemSide.Target)],
            Playbooks = usedPlaybooks,
            Mappings = mappings,
            OrphanSourceFields = orphans,
            Findings = findings,
            ChangeLog =
            [
                new()
                {
                    Version = options.Version,
                    Date = DateOnly.FromDateTime(createdAt.UtcDateTime),
                    Author = Author,
                    Description = $"Generated with {usedPlaybooks.Count} playbook(s): {mappings.Count(m => m.Type != MappingType.Unmapped)} of {mappings.Count} target field(s) mapped.",
                },
            ],
        };
    }

    private static OrphanSourceField Orphan(RecognisedField field) => new()
    {
        Field = Describe(field.Field, field.Repeats),
        SuggestedResolution = field.Detection is { } d
            ? $"Recognised as {d.BusinessConcept} by {d.Playbook}, but the target has no field for it; confirm it is not needed."
            : "No target field uses it; confirm it is not needed by the target.",
    };

    /// <summary>Profile conflicts (e.g. samples disagreeing on a type) on fields the mapping uses.</summary>
    private static IEnumerable<Finding> ProfileFindings(SystemProfile source, SystemProfile target, IReadOnlyList<FieldMapping> mappings)
    {
        var conflicts = new[] { ProfileFindingKind.TypeConflict, ProfileFindingKind.KindConflict, ProfileFindingKind.AmbiguousDateFormat, ProfileFindingKind.MixedFormats };
        return new[] { source, target }
            .SelectMany(p => p.Findings.Where(f => conflicts.Contains(f.Kind) && f.Path is not null).Select(f => (Profile: p, Finding: f)))
            .Select(x => (x.Profile, x.Finding, Ids: mappings
                .Where(m => m.Target.Path == x.Finding.Path || m.Sources.Any(s => s.Path == x.Finding.Path))
                .Select(m => m.Id).ToList()))
            .Where(x => x.Ids.Count > 0)
            .Select(x => new Finding
            {
                Id = "",
                Kind = FindingKind.Conflict,
                Description = $"{x.Profile.System} {x.Finding.Path}: {x.Finding.Message}",
                MappingIds = x.Ids,
                Sources = x.Finding.Inputs,
            });
    }

    public static FieldDescriptor Describe(ProfileField field, bool repeats = false) => new()
    {
        Name = field.Name,
        Path = field.Path,
        DataType = JsonName(field.DataType),
        Format = field.Format,
        Required = field.Required is Requirement.Required or Requirement.LikelyRequired,
        Cardinality = repeats ? Cardinality.Array : field.Cardinality,
        AllowedValues = field.AllowedValues,
        SampleValue = field.SampleValue,
        Description = field.Description,
    };

    internal static string JsonName<T>(T value) where T : struct, Enum => JsonNamingPolicy.CamelCase.ConvertName(value.ToString());

    private static SystemRef SystemRef(SystemProfile profile) => new()
    {
        Name = profile.System,
        Version = profile.Version ?? "unversioned",
        Format = profile.Format,
        Description = profile.Description,
    };

    private static IEnumerable<InputArtifact> Inputs(SystemProfile profile, SystemSide side) =>
        profile.Inputs.Select(i => new InputArtifact { Name = i.Name, Kind = i.Kind, Side = side, Notes = i.Notes });

    private static string Slug(string name)
    {
        var slug = string.Concat(name.ToLowerInvariant().Select(c => char.IsLetterOrDigit(c) ? c : '-'));
        while (slug.Contains("--", StringComparison.Ordinal))
        {
            slug = slug.Replace("--", "-", StringComparison.Ordinal);
        }

        return slug.Trim('-');
    }
}
