using System.Text.Json;
using MapWright.Core.Playbooks;
using MapWright.Core.Profile;
using MapWright.Core.Spec;

namespace MapWright.Core.Matching;

public sealed record MappingOptions
{
    /// <summary>Default: "&lt;source&gt;__&lt;target&gt;" from the system names.</summary>
    public string? Id { get; init; }
    public string? Title { get; init; }
    public string Version { get; init; } = "0.1.0";

    /// <summary>Default: now.</summary>
    public DateTimeOffset? CreatedAt { get; init; }
    public ConfidencePolicy ConfidencePolicy { get; init; } = new();
}

/// <summary>
/// Generates a mapping spec from a source and a target profile: one row per target value field, paired with
/// source fields through the business concepts the domain playbooks recognise on both sides.
/// </summary>
public static class MappingGenerator
{
    public const string Author = "MapWright";

    public static MappingDocument Generate(SystemProfile source, SystemProfile target, PlaybookLibrary library, MappingOptions? options = null)
    {
        options ??= new();
        var builder = new MappingBuilder(RecognisedField.From(source, library), library, options.ConfidencePolicy);
        var targets = RecognisedField.From(target, library);
        var mappings = targets.Select((t, i) => builder.Map(t, $"M{i + 1:000}")).ToList();

        var createdAt = options.CreatedAt ?? DateTimeOffset.UtcNow;
        var usedPlaybooks = library.Active
            .Where(p => p.Process is not null || mappings.Any(m => m.DomainPlaybook == p.Reference))
            .Select(p => new PlaybookRef { Name = p.Id, Version = p.Version })
            .ToList();

        return new()
        {
            SpecVersion = MappingDocument.CurrentSpecVersion,
            Id = options.Id ?? $"{Slug(source.System)}__{Slug(target.System)}",
            Title = options.Title ?? $"{source.System} → {target.System} mapping",
            Version = options.Version,
            CreatedAt = createdAt,
            Description = $"Generated by {Author} from the {source.System} and {target.System} profiles.",
            Source = SystemRef(source),
            Target = SystemRef(target),
            ConfidencePolicy = options.ConfidencePolicy,
            Inputs = [.. Inputs(source, SystemSide.Source), .. Inputs(target, SystemSide.Target)],
            Playbooks = usedPlaybooks,
            Mappings = mappings,
            ChangeLog =
            [
                new()
                {
                    Version = options.Version,
                    Date = DateOnly.FromDateTime(createdAt.UtcDateTime),
                    Author = Author,
                    Description = $"Generated with {usedPlaybooks.Count} playbook(s): {mappings.Count(m => m.Type != MappingType.Unmapped)} of {mappings.Count} target field(s) mapped.",
                },
            ],
        };
    }

    public static FieldDescriptor Describe(ProfileField field, bool repeats = false) => new()
    {
        Name = field.Name,
        Path = field.Path,
        DataType = JsonName(field.DataType),
        Format = field.Format,
        Required = field.Required is Requirement.Required or Requirement.LikelyRequired,
        Cardinality = repeats ? Cardinality.Array : field.Cardinality,
        AllowedValues = field.AllowedValues,
        SampleValue = field.SampleValue,
        Description = field.Description,
    };

    internal static string JsonName<T>(T value) where T : struct, Enum => JsonNamingPolicy.CamelCase.ConvertName(value.ToString());

    private static SystemRef SystemRef(SystemProfile profile) => new()
    {
        Name = profile.System,
        Version = profile.Version ?? "unversioned",
        Format = profile.Format,
        Description = profile.Description,
    };

    private static IEnumerable<InputArtifact> Inputs(SystemProfile profile, SystemSide side) =>
        profile.Inputs.Select(i => new InputArtifact { Name = i.Name, Kind = i.Kind, Side = side, Notes = i.Notes });

    private static string Slug(string name)
    {
        var slug = string.Concat(name.ToLowerInvariant().Select(c => char.IsLetterOrDigit(c) ? c : '-'));
        while (slug.Contains("--", StringComparison.Ordinal))
        {
            slug = slug.Replace("--", "-", StringComparison.Ordinal);
        }

        return slug.Trim('-');
    }
}
